/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as DevlogIndexImport } from './routes/devlog/index'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as DevlogIdImport } from './routes/devlog/$id'
import { Route as LayoutContactImport } from './routes/_layout/contact'
import { Route as LayoutTeamIndexImport } from './routes/_layout/team/index'
import { Route as LayoutGamesIndexImport } from './routes/_layout/games/index'
import { Route as LayoutGamesSlugImport } from './routes/_layout/games/$slug'
import { Route as LayoutTeamTeamMemberImport } from './routes/_layout/team/$team.$member'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const DevlogIndexRoute = DevlogIndexImport.update({
  id: '/devlog/',
  path: '/devlog/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const DevlogIdRoute = DevlogIdImport.update({
  id: '/devlog/$id',
  path: '/devlog/$id',
  getParentRoute: () => rootRoute,
} as any)

const LayoutContactRoute = LayoutContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamIndexRoute = LayoutTeamIndexImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesIndexRoute = LayoutGamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesSlugRoute = LayoutGamesSlugImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamTeamMemberRoute = LayoutTeamTeamMemberImport.update({
  id: '/team/$team/$member',
  path: '/team/$team/$member',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactImport
      parentRoute: typeof LayoutImport
    }
    '/devlog/$id': {
      id: '/devlog/$id'
      path: '/devlog/$id'
      fullPath: '/devlog/$id'
      preLoaderRoute: typeof DevlogIdImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/devlog/': {
      id: '/devlog/'
      path: '/devlog'
      fullPath: '/devlog'
      preLoaderRoute: typeof DevlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/games/$slug': {
      id: '/_layout/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof LayoutGamesSlugImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/': {
      id: '/_layout/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof LayoutGamesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team/': {
      id: '/_layout/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team/$team/$member': {
      id: '/_layout/team/$team/$member'
      path: '/team/$team/$member'
      fullPath: '/team/$team/$member'
      preLoaderRoute: typeof LayoutTeamTeamMemberImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGamesSlugRoute: typeof LayoutGamesSlugRoute
  LayoutGamesIndexRoute: typeof LayoutGamesIndexRoute
  LayoutTeamIndexRoute: typeof LayoutTeamIndexRoute
  LayoutTeamTeamMemberRoute: typeof LayoutTeamTeamMemberRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutContactRoute: LayoutContactRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGamesSlugRoute: LayoutGamesSlugRoute,
  LayoutGamesIndexRoute: LayoutGamesIndexRoute,
  LayoutTeamIndexRoute: LayoutTeamIndexRoute,
  LayoutTeamTeamMemberRoute: LayoutTeamTeamMemberRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/contact': typeof LayoutContactRoute
  '/devlog/$id': typeof DevlogIdRoute
  '/': typeof LayoutIndexRoute
  '/devlog': typeof DevlogIndexRoute
  '/games/$slug': typeof LayoutGamesSlugRoute
  '/games': typeof LayoutGamesIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/team/$team/$member': typeof LayoutTeamTeamMemberRoute
}

export interface FileRoutesByTo {
  '/contact': typeof LayoutContactRoute
  '/devlog/$id': typeof DevlogIdRoute
  '/': typeof LayoutIndexRoute
  '/devlog': typeof DevlogIndexRoute
  '/games/$slug': typeof LayoutGamesSlugRoute
  '/games': typeof LayoutGamesIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/team/$team/$member': typeof LayoutTeamTeamMemberRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/contact': typeof LayoutContactRoute
  '/devlog/$id': typeof DevlogIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/devlog/': typeof DevlogIndexRoute
  '/_layout/games/$slug': typeof LayoutGamesSlugRoute
  '/_layout/games/': typeof LayoutGamesIndexRoute
  '/_layout/team/': typeof LayoutTeamIndexRoute
  '/_layout/team/$team/$member': typeof LayoutTeamTeamMemberRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/contact'
    | '/devlog/$id'
    | '/'
    | '/devlog'
    | '/games/$slug'
    | '/games'
    | '/team'
    | '/team/$team/$member'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/devlog/$id'
    | '/'
    | '/devlog'
    | '/games/$slug'
    | '/games'
    | '/team'
    | '/team/$team/$member'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/contact'
    | '/devlog/$id'
    | '/_layout/'
    | '/devlog/'
    | '/_layout/games/$slug'
    | '/_layout/games/'
    | '/_layout/team/'
    | '/_layout/team/$team/$member'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  DevlogIdRoute: typeof DevlogIdRoute
  DevlogIndexRoute: typeof DevlogIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  DevlogIdRoute: DevlogIdRoute,
  DevlogIndexRoute: DevlogIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/devlog/$id",
        "/devlog/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/contact",
        "/_layout/",
        "/_layout/games/$slug",
        "/_layout/games/",
        "/_layout/team/",
        "/_layout/team/$team/$member"
      ]
    },
    "/_layout/contact": {
      "filePath": "_layout/contact.tsx",
      "parent": "/_layout"
    },
    "/devlog/$id": {
      "filePath": "devlog/$id.tsx"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/devlog/": {
      "filePath": "devlog/index.tsx"
    },
    "/_layout/games/$slug": {
      "filePath": "_layout/games/$slug.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/": {
      "filePath": "_layout/games/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/team/": {
      "filePath": "_layout/team/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/team/$team/$member": {
      "filePath": "_layout/team/$team.$member.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
