/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TeamImport } from './routes/team'
import { Route as GamesImport } from './routes/games'
import { Route as ContactImport } from './routes/contact'
import { Route as IndexImport } from './routes/index'
import { Route as GamesTracklineImport } from './routes/games/trackline'
import { Route as GamesTheLastDinerImport } from './routes/games/the-last-diner'
import { Route as GamesNoellesArkImport } from './routes/games/noelles-ark'

// Create/Update Routes

const TeamRoute = TeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRoute,
} as any)

const GamesRoute = GamesImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesTracklineRoute = GamesTracklineImport.update({
  id: '/trackline',
  path: '/trackline',
  getParentRoute: () => GamesRoute,
} as any)

const GamesTheLastDinerRoute = GamesTheLastDinerImport.update({
  id: '/the-last-diner',
  path: '/the-last-diner',
  getParentRoute: () => GamesRoute,
} as any)

const GamesNoellesArkRoute = GamesNoellesArkImport.update({
  id: '/noelles-ark',
  path: '/noelles-ark',
  getParentRoute: () => GamesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesImport
      parentRoute: typeof rootRoute
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamImport
      parentRoute: typeof rootRoute
    }
    '/games/noelles-ark': {
      id: '/games/noelles-ark'
      path: '/noelles-ark'
      fullPath: '/games/noelles-ark'
      preLoaderRoute: typeof GamesNoellesArkImport
      parentRoute: typeof GamesImport
    }
    '/games/the-last-diner': {
      id: '/games/the-last-diner'
      path: '/the-last-diner'
      fullPath: '/games/the-last-diner'
      preLoaderRoute: typeof GamesTheLastDinerImport
      parentRoute: typeof GamesImport
    }
    '/games/trackline': {
      id: '/games/trackline'
      path: '/trackline'
      fullPath: '/games/trackline'
      preLoaderRoute: typeof GamesTracklineImport
      parentRoute: typeof GamesImport
    }
  }
}

// Create and export the route tree

interface GamesRouteChildren {
  GamesNoellesArkRoute: typeof GamesNoellesArkRoute
  GamesTheLastDinerRoute: typeof GamesTheLastDinerRoute
  GamesTracklineRoute: typeof GamesTracklineRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesNoellesArkRoute: GamesNoellesArkRoute,
  GamesTheLastDinerRoute: GamesTheLastDinerRoute,
  GamesTracklineRoute: GamesTracklineRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRouteWithChildren
  '/team': typeof TeamRoute
  '/games/noelles-ark': typeof GamesNoellesArkRoute
  '/games/the-last-diner': typeof GamesTheLastDinerRoute
  '/games/trackline': typeof GamesTracklineRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRouteWithChildren
  '/team': typeof TeamRoute
  '/games/noelles-ark': typeof GamesNoellesArkRoute
  '/games/the-last-diner': typeof GamesTheLastDinerRoute
  '/games/trackline': typeof GamesTracklineRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/games': typeof GamesRouteWithChildren
  '/team': typeof TeamRoute
  '/games/noelles-ark': typeof GamesNoellesArkRoute
  '/games/the-last-diner': typeof GamesTheLastDinerRoute
  '/games/trackline': typeof GamesTracklineRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/games'
    | '/team'
    | '/games/noelles-ark'
    | '/games/the-last-diner'
    | '/games/trackline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/games'
    | '/team'
    | '/games/noelles-ark'
    | '/games/the-last-diner'
    | '/games/trackline'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/games'
    | '/team'
    | '/games/noelles-ark'
    | '/games/the-last-diner'
    | '/games/trackline'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GamesRoute: typeof GamesRouteWithChildren
  TeamRoute: typeof TeamRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GamesRoute: GamesRouteWithChildren,
  TeamRoute: TeamRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/contact",
        "/games",
        "/team"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/games": {
      "filePath": "games.tsx",
      "children": [
        "/games/noelles-ark",
        "/games/the-last-diner",
        "/games/trackline"
      ]
    },
    "/team": {
      "filePath": "team.tsx"
    },
    "/games/noelles-ark": {
      "filePath": "games/noelles-ark.tsx",
      "parent": "/games"
    },
    "/games/the-last-diner": {
      "filePath": "games/the-last-diner.tsx",
      "parent": "/games"
    },
    "/games/trackline": {
      "filePath": "games/trackline.tsx",
      "parent": "/games"
    }
  }
}
ROUTE_MANIFEST_END */
