/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutContactImport } from './routes/_layout/contact'
import { Route as LayoutTeamIndexImport } from './routes/_layout/team/index'
import { Route as LayoutGamesIndexImport } from './routes/_layout/games/index'
import { Route as LayoutGamesTracklineImport } from './routes/_layout/games/trackline'
import { Route as LayoutGamesTheLastDinerImport } from './routes/_layout/games/the-last-diner'
import { Route as LayoutGamesNoellesArkImport } from './routes/_layout/games/noelles-ark'
import { Route as LayoutTeamTeamMemberImport } from './routes/_layout/team/$team.$member'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutContactRoute = LayoutContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamIndexRoute = LayoutTeamIndexImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesIndexRoute = LayoutGamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesTracklineRoute = LayoutGamesTracklineImport.update({
  id: '/games/trackline',
  path: '/games/trackline',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesTheLastDinerRoute = LayoutGamesTheLastDinerImport.update({
  id: '/games/the-last-diner',
  path: '/games/the-last-diner',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGamesNoellesArkRoute = LayoutGamesNoellesArkImport.update({
  id: '/games/noelles-ark',
  path: '/games/noelles-ark',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTeamTeamMemberRoute = LayoutTeamTeamMemberImport.update({
  id: '/team/$team/$member',
  path: '/team/$team/$member',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/noelles-ark': {
      id: '/_layout/games/noelles-ark'
      path: '/games/noelles-ark'
      fullPath: '/games/noelles-ark'
      preLoaderRoute: typeof LayoutGamesNoellesArkImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/the-last-diner': {
      id: '/_layout/games/the-last-diner'
      path: '/games/the-last-diner'
      fullPath: '/games/the-last-diner'
      preLoaderRoute: typeof LayoutGamesTheLastDinerImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/trackline': {
      id: '/_layout/games/trackline'
      path: '/games/trackline'
      fullPath: '/games/trackline'
      preLoaderRoute: typeof LayoutGamesTracklineImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/games/': {
      id: '/_layout/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof LayoutGamesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team/': {
      id: '/_layout/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/team/$team/$member': {
      id: '/_layout/team/$team/$member'
      path: '/team/$team/$member'
      fullPath: '/team/$team/$member'
      preLoaderRoute: typeof LayoutTeamTeamMemberImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutGamesNoellesArkRoute: typeof LayoutGamesNoellesArkRoute
  LayoutGamesTheLastDinerRoute: typeof LayoutGamesTheLastDinerRoute
  LayoutGamesTracklineRoute: typeof LayoutGamesTracklineRoute
  LayoutGamesIndexRoute: typeof LayoutGamesIndexRoute
  LayoutTeamIndexRoute: typeof LayoutTeamIndexRoute
  LayoutTeamTeamMemberRoute: typeof LayoutTeamTeamMemberRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutContactRoute: LayoutContactRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutGamesNoellesArkRoute: LayoutGamesNoellesArkRoute,
  LayoutGamesTheLastDinerRoute: LayoutGamesTheLastDinerRoute,
  LayoutGamesTracklineRoute: LayoutGamesTracklineRoute,
  LayoutGamesIndexRoute: LayoutGamesIndexRoute,
  LayoutTeamIndexRoute: LayoutTeamIndexRoute,
  LayoutTeamTeamMemberRoute: LayoutTeamTeamMemberRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/contact': typeof LayoutContactRoute
  '/': typeof LayoutIndexRoute
  '/games/noelles-ark': typeof LayoutGamesNoellesArkRoute
  '/games/the-last-diner': typeof LayoutGamesTheLastDinerRoute
  '/games/trackline': typeof LayoutGamesTracklineRoute
  '/games': typeof LayoutGamesIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/team/$team/$member': typeof LayoutTeamTeamMemberRoute
}

export interface FileRoutesByTo {
  '/contact': typeof LayoutContactRoute
  '/': typeof LayoutIndexRoute
  '/games/noelles-ark': typeof LayoutGamesNoellesArkRoute
  '/games/the-last-diner': typeof LayoutGamesTheLastDinerRoute
  '/games/trackline': typeof LayoutGamesTracklineRoute
  '/games': typeof LayoutGamesIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/team/$team/$member': typeof LayoutTeamTeamMemberRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/games/noelles-ark': typeof LayoutGamesNoellesArkRoute
  '/_layout/games/the-last-diner': typeof LayoutGamesTheLastDinerRoute
  '/_layout/games/trackline': typeof LayoutGamesTracklineRoute
  '/_layout/games/': typeof LayoutGamesIndexRoute
  '/_layout/team/': typeof LayoutTeamIndexRoute
  '/_layout/team/$team/$member': typeof LayoutTeamTeamMemberRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/contact'
    | '/'
    | '/games/noelles-ark'
    | '/games/the-last-diner'
    | '/games/trackline'
    | '/games'
    | '/team'
    | '/team/$team/$member'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/'
    | '/games/noelles-ark'
    | '/games/the-last-diner'
    | '/games/trackline'
    | '/games'
    | '/team'
    | '/team/$team/$member'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/contact'
    | '/_layout/'
    | '/_layout/games/noelles-ark'
    | '/_layout/games/the-last-diner'
    | '/_layout/games/trackline'
    | '/_layout/games/'
    | '/_layout/team/'
    | '/_layout/team/$team/$member'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/contact",
        "/_layout/",
        "/_layout/games/noelles-ark",
        "/_layout/games/the-last-diner",
        "/_layout/games/trackline",
        "/_layout/games/",
        "/_layout/team/",
        "/_layout/team/$team/$member"
      ]
    },
    "/_layout/contact": {
      "filePath": "_layout/contact.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/noelles-ark": {
      "filePath": "_layout/games/noelles-ark.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/the-last-diner": {
      "filePath": "_layout/games/the-last-diner.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/trackline": {
      "filePath": "_layout/games/trackline.tsx",
      "parent": "/_layout"
    },
    "/_layout/games/": {
      "filePath": "_layout/games/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/team/": {
      "filePath": "_layout/team/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/team/$team/$member": {
      "filePath": "_layout/team/$team.$member.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
